const UserConstants = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGIN_REQUEST: "LOGIN_REQUEST",

    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    REGISTER_USER_FAIL: "REGISTER_USER_FAIL",
    REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST",

    LOAD_USER_REQUEST: "LOAD_USER_REQUEST",
    LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",

    USER_LOGGEDOUT_TRUE: "USER_LOGGEDOUT_TRUE",
    USER_LOGGEDOUT_REQUEST: "USER_LOGGEDOUT_REQUEST",
    USER_LOGGEDOUT_FALSE: "USER_LOGGEDOUT_FALSE",

    USER_UPDATED_SUCCESS: "USER_UPDATED_SUCCESS",
    USER_UPDATED_FAIL: "USER_UPDATED_FAIL",

    LOADING: "LOADING"
}

export default UserConstants